params:
  - params.yaml

stages:
  data_ingestion:
    cmd: python -m ml.comment_sentiment.ingestion
    deps:
      - ml/comment_sentiment/ingestion.py
    params:
      - dataset
      - ingestion
    outs:
      - ${ingestion.processed_train_path}
      - ${ingestion.processed_test_path}

  model_building:
    cmd: python -m ml.comment_sentiment.building
    deps:
      - ${ingestion.processed_train_path}
      - ml/comment_sentiment/building.py
    params:
      - model
      - vectorizer
    outs:
      - ${pipeline.path}

  model_evaluation:
    cmd: python -m ml.comment_sentiment.evaluation
    deps:
      - ${ingestion.processed_test_path}
      - ${pipeline.path}
      - ml/comment_sentiment/evaluation.py
    params:
      - evaluation
    outs:
      - mlflow_run_info.json
